=== 892003867/learn-java/02-XML&tomcat/src/_01_XML/_01_XML/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!--
         模拟servlet2.3规范，如果开发人员需要在xml使用当前DTD约束，必须包括DOCTYPE。
            格式如下：
            <!DOCTYPE web-app SYSTEM "web-app_2_3.dtd">
        -->
        <!--
            *：          出现多次
            ?：          0次或者1次
            +：          最少出现1次或者多次
            |：          选择两者之一
            ()：         用来给元素分组
            ,：          表示按照顺序出现
             (#PCDATA)： 该内容模型说明元素中可以同时出现文本和元素.
        -->
        <!ELEMENT web-app (servlet*,servlet-mapping* , welcome-file-list?) >
        <!ELEMENT servlet (servlet-name,description?,(servlet-class|jsp-file))>
        <!ELEMENT servlet-mapping (servlet-name,url-pattern+) >
        <!ELEMENT servlet-name (#PCDATA)>
        <!ELEMENT servlet-class (#PCDATA)>
        <!ELEMENT url-pattern (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT jsp-file (#PCDATA)>
        <!ELEMENT welcome-file-list (welcome-file+)>
        <!ELEMENT welcome-file (#PCDATA)>
        <!ATTLIST web-app version CDATA #IMPLIED>

=== 892003867/learn-java/02-XML&tomcat/src/_01_XML/_01_XML/test.xml
<?xml version="1.0"?>
<!--
     xmlns：                               空间命名，url可以自定义，也可以使用约束url
     xmlns:xsi：                           使用xs做为前缀
     xsi:schemaLocation：                  导入本地约束文件，约束当前xml使用的标签
     <!DOCTYPE web-app SYSTEM "test.dtd">：导入本地约束文件
     <![cdata[ 转成字符形式 ]]>：            不会被浏览器解析
-->

<web-app xmlns="http://www.baidu.com"
         xmlns:xsi="http://www.baidu.com"
         xsi:schemaLocation="test.dtd">
    <servlet>
        <servlet-name></servlet-name>
        <description></description>
        <servlet-class></servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>qewe</servlet-name>
        <url-pattern></url-pattern>
    </servlet-mapping>
    <welcome-file-list>
        <welcome-file></welcome-file>
    </welcome-file-list>

    <![CDATA[
        if(int i=0;i<5;i++){
            System.out.println(i);
        }
    ]]>
</web-app>
